In [1]:
import pandas as pd
import requests

In [2]:

df = pd.read_csv('BTCfiltere_data_intereactivechart.csv')
df

        BTC_Date     BTC_Close    VIX_Date
0     2015-08-22    230.389999  2015-08-21
1     2015-08-23    228.169006  2015-08-21
2     2015-08-24    210.494995  2015-08-21
3     2015-08-25    221.608994  2015-08-21
4     2015-08-26    225.830994  2015-08-21
...          ...           ...         ...
1345  2024-08-31  58969.898438  2024-08-05
1346  2024-09-01  57325.488281  2024-08-05
1347  2024-09-02  59112.480469  2024-08-05
1348  2024-09-03  57431.023438  2024-08-05
1349  2024-09-04  57971.539062  2024-08-05

[1350 rows x 3 columns]

In [7]:

df['BTC_Date'] = pd.to_datetime(df['BTC_Date'])

#group by vix date 
change30day = df.groupby('VIX_Date').apply(
    lambda x: ((x.iloc[-1]['BTC_Close'] - x.iloc[0]['BTC_Close']) / x.iloc[0]['BTC_Close']) * 100
).reset_index(name='change30day')

change30day.head(10)


change30day.to_csv('30day_percentagechange_fromspikechart.csv', index=False) 
change30day.head(10)

C:\Users\herbd\AppData\Local\Temp\ipykernel_13896\2457764078.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  change30day = df.groupby('VIX_Date').apply(

     VIX_Date  change30day
0  2015-08-21     0.356789
1  2015-09-09     2.287011
2  2015-09-28    28.700780
3  2016-01-08   -15.859976
4  2016-01-13   -10.700060
5  2016-01-15     5.081850
6  2016-02-08    10.326596
7  2016-06-24    -0.577038
8  2018-02-05    28.521670
9  2018-10-24   -32.876541