In [1]:
import pandas as pd
import requests

In [2]:

df = pd.read_csv('CorrolationBTC_GOLD_BTC_VIX_dataFINAL(7).csv')
df

,date,Price(USD$ / Ounce),BTC_USD$_x,Rolling_Corr_GOLD_BTC,VIX_value,BTC_USD$_y,Rolling_Corr_VIX_BTC
0,2014-12-01,1210.43,370.00,NaN,14.29,370.00,NaN
1,2014-12-02,1198.56,378.00,NaN,12.85,378.00,NaN
2,2014-12-03,1209.19,378.00,NaN,12.47,378.00,NaN
3,2014-12-04,1205.32,377.10,NaN,12.38,377.10,NaN
4,2014-12-08,1202.80,375.00,NaN,14.21,375.00,NaN
...,...,...,...,...,...,...,...
2463,2024-09-20,2621.96,63362.74,-0.199595,16.15,63362.74,-0.351948
2464,2024-09-23,2628.40,64272.93,-0.132648,15.89,64272.93,-0.340176
2465,2024-09-24,2656.70,63130.89,-0.083288,15.39,63130.89,-0.330372
2466,2024-09-25,2656.82,65177.21,-0.016074,15.41,65177.21,-0.321177
2467,2024-09-26,2671.59,65789.00,0.049718,15.37,65789.00,-0.314256

In [9]:
df1 = df[['date', 'Rolling_Corr_GOLD_BTC', 'Rolling_Corr_VIX_BTC']]


df1

            date  Rolling_Corr_GOLD_BTC  Rolling_Corr_VIX_BTC
0     2014-12-01                    NaN                   NaN
1     2014-12-02                    NaN                   NaN
2     2014-12-03                    NaN                   NaN
3     2014-12-04                    NaN                   NaN
4     2014-12-08                    NaN                   NaN
...          ...                    ...                   ...
2463  2024-09-20              -0.199595             -0.351948
2464  2024-09-23              -0.132648             -0.340176
2465  2024-09-24              -0.083288             -0.330372
2466  2024-09-25              -0.016074             -0.321177
2467  2024-09-26               0.049718             -0.314256

[2468 rows x 3 columns]

In [13]:
import pandas as pd

df1['date'] = pd.to_datetime(df1['date'])

df1['year'] = df1['date'].dt.year

corrAvg = df1.groupby('year')[['Rolling_Corr_GOLD_BTC', 'Rolling_Corr_VIX_BTC']].mean()

corrAvg = corrAvg[corrAvg.index != 2014]
corrAvg

C:\Users\herbd\AppData\Local\Temp\ipykernel_6988\3475584350.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['date'] = pd.to_datetime(df1['date'])
C:\Users\herbd\AppData\Local\Temp\ipykernel_6988\3475584350.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['year'] = df1['date'].dt.year

      Rolling_Corr_GOLD_BTC  Rolling_Corr_VIX_BTC
year
2015              -0.501319             -0.182644
2016              -0.028005              0.123856
2017               0.154473             -0.110458
2018              -0.061946             -0.305240
2019               0.065610              0.023515
2020               0.369301             -0.473949
2021              -0.252565             -0.178352
2022               0.257856             -0.377048
2023               0.382856             -0.217637
2024               0.296845             -0.113058

In [22]:
corrAvg = corrAvg.drop(columns=['index'])

# Rename the remaining columns
corrAvg.columns = ['Year', 'Rolling_Corr_GOLD_BTC', 'Rolling_Corr_VIX_BTC']

# Verify the structure
print(corrAvg.head())

   Year  Rolling_Corr_GOLD_BTC  Rolling_Corr_VIX_BTC
0  2015              -0.501319             -0.182644
1  2016              -0.028005              0.123856
2  2017               0.154473             -0.110458
3  2018              -0.061946             -0.305240
4  2019               0.065610              0.023515

In [23]:
# Reset index so 'year' is a regular column
corrAvg.reset_index(drop=True, inplace=True)
corrAvg.head(10)

# Rename the columns to ensure proper headers
corrAvg.columns = ['Year', 'Rolling_Corr_GOLD_BTC', 'Rolling_Corr_VIX_BTC']
corrAvg

   Year  Rolling_Corr_GOLD_BTC  Rolling_Corr_VIX_BTC
0  2015              -0.501319             -0.182644
1  2016              -0.028005              0.123856
2  2017               0.154473             -0.110458
3  2018              -0.061946             -0.305240
4  2019               0.065610              0.023515
5  2020               0.369301             -0.473949
6  2021              -0.252565             -0.178352
7  2022               0.257856             -0.377048
8  2023               0.382856             -0.217637
9  2024               0.296845             -0.113058

In [24]:

corrAvg.to_csv("correlationchartAVERAGES(2).csv", index=False)
corrAvg

   Year  Rolling_Corr_GOLD_BTC  Rolling_Corr_VIX_BTC
0  2015              -0.501319             -0.182644
1  2016              -0.028005              0.123856
2  2017               0.154473             -0.110458
3  2018              -0.061946             -0.305240
4  2019               0.065610              0.023515
5  2020               0.369301             -0.473949
6  2021              -0.252565             -0.178352
7  2022               0.257856             -0.377048
8  2023               0.382856             -0.217637
9  2024               0.296845             -0.113058